polaris.authentication.type=mixed

quarkus.oidc.tenant-enabled=true
quarkus.oidc.auth-server-url=http://keycloak:8080/realms/Viewer
quarkus.oidc.client-id=polaris-client
quarkus.oidc.credentials.secret=oQCtaJ0XIpXzQWZl8os71q5aztSZ6YPD
quarkus.oidc.token.issuer=any
quarkus.oidc.roles.role-claim-path=realm_access/roles

polaris.oidc.principal-mapper.type=default
polaris.oidc.principal-mapper.id-claim-path=principal_id
polaris.oidc.principal-mapper.name-claim-path=principal_name

polaris.oidc.principal-roles-mapper.type=default
polaris.oidc.principal-roles-mapper.filter=^service_admin$
polaris.oidc.principal-roles-mapper.mappings[0].regex=^.*$
polaris.oidc.principal-roles-mapper.mappings[0].replacement=PRINCIPAL_ROLE:$0

polaris.persistence.type=relational-jdbc
quarkus.datasource.username=polaris
quarkus.datasource.password=123
quarkus.datasource.jdbc.url=jdbc:postgresql://polaris-db:5432/POLARIS
