[agent]
  interval = "30s"
  flush_interval = "30s"
  debug = true

[[inputs.http]]
  urls = ["https://api.coingecko.com/api/v3/simple/price?ids=bitcoin,ethereum,solana&vs_currencies=usd&include_24hr_change=true&include_market_cap=true&include_24hr_vol=true"]
  name_override = "crypto_price"
  data_format = "json_v2"

  [[inputs.http.json_v2]]
    [[inputs.http.json_v2.field]]
      path = "bitcoin.usd"
      rename = "btc_price"
      type = "float"
    [[inputs.http.json_v2.field]]
      path = "bitcoin.usd_24h_change"
      rename = "btc_change_24h"
      type = "float"
    [[inputs.http.json_v2.field]]
      path = "bitcoin.usd_market_cap"
      rename = "btc_market_cap"
      type = "float"
    [[inputs.http.json_v2.field]]
      path = "bitcoin.usd_24h_vol"
      rename = "btc_volume_24h"
      type = "float"
    [[inputs.http.json_v2.field]]
      path = "ethereum.usd"
      rename = "eth_price"
      type = "float"
    [[inputs.http.json_v2.field]]
      path = "ethereum.usd_24h_change"
      rename = "eth_change_24h"
      type = "float"
    [[inputs.http.json_v2.field]]
      path = "ethereum.usd_market_cap"
      rename = "eth_market_cap"
      type = "float"
    [[inputs.http.json_v2.field]]
      path = "ethereum.usd_24h_vol"
      rename = "eth_volume_24h"
      type = "float"
    [[inputs.http.json_v2.field]]
      path = "solana.usd"
      rename = "sol_price"
      type = "float"
    [[inputs.http.json_v2.field]]
      path = "solana.usd_24h_change"
      rename = "sol_change_24h"
      type = "float"
    [[inputs.http.json_v2.field]]
      path = "solana.usd_market_cap"
      rename = "sol_market_cap"
      type = "float"
    [[inputs.http.json_v2.field]]
      path = "solana.usd_24h_vol"
      rename = "sol_volume_24h"
      type = "float"

[[outputs.influxdb_v2]]
  urls = ["http://influxdb:8086"]
  token = "123"
  organization = "sk"
  bucket = "telegraf"
